spring.application.name=BWM

# 만료 경매 자동 마감 스케줄러
# 이전 실행 종료 후 다음 실행까지 60초 대기
auction.scheduler.fixed-delay=60000

# 서버 시작 후 첫 실행까지 10초 대기
auction.scheduler.initial-delay=10000

# OpenAPI JSON path
springdoc.api-docs.path=/v3/api-docs

# Swagger UI path
springdoc.swagger-ui.path=/swagger-ui.html

# Swagger UI settings
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.doc-expansion=none